author: Chris Zuber
title: Whiskey Flat Days
url: 'https://whiskeyflatdays.com'
markdown: kramdown
version: 2.1.0
timezone: America/Los_Angeles
lang: en
dir: ltr
charset: utf-8
paginate: 8
paginate_path: "/page-:num/"
viewport: width=device-width
robots: 'follow, index'
referrer: no-referrer
manifest: /webapp.webmanifest
tiles-config: /browserconfig.xml
service_worker: '/service-worker.js'
keep-kern-clean: true
og-type: website
disqus: whiskey-flat-days
description: "Map, events, and news app for Whiskey Flat Days"
thumbnail:
  url: https://i.imgur.com/Qnvw7I2l.jpg
mobile-web-app-capable: true
canonical: 'https://whiskeyflatdays.com'
keywords:
  - whiskey flat
  - kernville
  - kern valley
  - kern river valley
  - festival
  - events
  - parade
  - rodeo
  - events
  - vendor
repository:
  username: kernvalley
  project: whiskey-flat-days
  title: Whiskey Flat Days
social:
  url: https://kernvalley.us
  twitter: kern_valley
  linkedin: company/kernvalley-us
  facebook: KernValley.us
# feed:
#   url: /feed.rss
#   type: application/rss+xml
icons: '/img/icons.svg'
theme-color: '#b70c0c'
background-color: '#242424'
# discus-identifier:
google-analytics: UA-156441506-1
# ad-sense:
# webmaster-verifications:
#   google:
#   bing:
defaults:
- scope:
    path: _posts
  values:
    no-header: true
    layout: post
    author:
      givenName: Chris
      familyName: Zuber
      url: 'https://shgysk8zer0.github.io'
      gravatar: '43578597e449298f5488c2407c8a8ae5'
      github: shgysk8zer0
      twitter: shgysk8zer0
      linkedin: chris-zuber-455346141/
    publisher:
      name: 'KernValley.US'
      url: 'https://kernvalley.us'
      logo:
        url: 'https://kernvalley.us/img/icon-256.png'
    permalink: /news/:categories/:year/:month/:day/:title
    comments: true
    ads: false
    index: true
- scope:
    path: _drafts
  values:
    no-header: true
    layout: post
    author:
      givenName: Chris
      familyName: Zuber
      url: 'https://shgysk8zer0.github.io'
      gravatar: '43578597e449298f5488c2407c8a8ae5'
      github: 'shgysk8zer0'
      twitter: shgysk8zer0
    publisher:
      name: 'KernValley.US'
      url: 'https://kernvalley.us'
      logo:
              url: 'https://kernvalley.us/img/icon-256.png'
    permalink: /news/:categories/:year/:month/:day/:title
    comments: false
    ads: false
plugins:
- jekyll-gist
- jekyll-youtube
- jekyll-admin
- jekyll-watch
- jekyll-paginate
include:
# Folders with dotfiles are ignored by default.
- .well-known
- _headers
- _redirects
exclude:
- ".gitkeep"
- "*.rb"
- "*.gemspec"
- "*.php"
- "*.sh"
- "*.csv"
- "*.sfd"
- "*.ai"
- "*.psd"
- "*.sketch"
- "*.yml"
- "*.lock"
- "*.log"
- "*.config.js"
- ".gitkeep"
- docs/
- "/*-theme.xml"
- "/.github/"
- Gemfile
- node_modules/
- palette.xml
- README.md
- LICENSE
- "/img/octicons/*.md"
- "/img/octicons/LICENSE"
- "/img/octicons/script"
- "/img/adwaita-icons/docs"
- "/img/adwaita-icons/LICENSE"
