author: Chris Zuber
title: Whiskey Flat Days
url: 'https://whiskeyflatdays.com'
markdown: kramdown
version: 3.0.9
timezone: America/Los_Angeles
lang: en
dir: ltr
charset: utf-8
paginate: 8
paginate_path: "/news/:num/"
viewport: width=device-width
robots: 'follow, index'
referrer: no-referrer
manifest: /webapp.webmanifest
tiles-config: /browserconfig.xml
service_worker: '/service-worker.js'
keep-kern-clean: true
og-type: website
disqus: whiskey-flat-days
description: "Map, events, and news app for Whiskey Flat Days"
thumbnail:
  url: /img/raster/pwa-640.png
  height: 360
  width: 640
mobile-web-app-capable: true
canonical: https://whiskeyflatdays.com
keywords:
  - whiskey flat days
  - whiskey flats
  - kernville
  - kern valley
  - kern river valley
  - festival
  - events
  - parade
  - rodeo
  - events
  - vendor
repository:
  username: kernvalley
  project: whiskey-flat-days
  title: Whiskey Flat Days
social:
  url: https://kernvalley.us
  twitter: kern_valley
  linkedin: company/kernvalley-us
  facebook: KernValley.us
feed:
  url: /feed.rss
  type: application/rss+xml
icons: '/img/icons.svg'
theme-color: '#b70c0c'
background-color: '#242424'
# discus-identifier:
google-analytics: UA-156441506-1
# ad-sense:
webmaster-verifications:
#   google:
  bing: 14343D3F998AB3FEE56B299A7F3E5CDB
collections:
  mayors:
    output: true
    permalink: /:collection/:title
    layout: mayor
defaults:
- scope:
    path: _posts
  values:
    no-header: true
    layout: post
    author: Chris
    publisher:
      name: 'KernValley.US'
      url: 'https://kernvalley.us'
      logo:
        url: 'https://kernvalley.us/img/icon-256.png'
    permalink: /news/:categories/:year/:month/:day/:title
    referrer: origin
    comments: true
    ads: false
    index: true
- scope:
    path: _drafts
  values:
    no-header: true
    layout: post
    author: Chris
    publisher:
      name: 'KernValley.US'
      url: 'https://kernvalley.us'
      logo:
        url: 'https://kernvalley.us/img/icon-256.png'
    permalink: /news/:categories/:year/:month/:day/:title
    comments: false
    ads: false
plugins:
  - jekyll-admin
  - jekyll-watch
  - jekyll-paginate
include:
  # Folders with dotfiles are ignored by default.
  - .well-known
  - _headers
  - _redirects
exclude:
  - CHANGELOG.md
  - netlify.toml
  - "/api/*"
  - "./.netlify/"
  - "./.netlify/*"
  - ".gitkeep"
  - "*.rb"
  - "*.gemspec"
  - "*.php"
  - "*.sh"
  - "*.csv"
  - "*.sfd"
  - "*.ai"
  - "*.psd"
  - "*.sketch"
  - "*.yml"
  - "*.lock"
  - "*.log"
  - "tags.*"
  - "*.config.js"
  - docs/
  - "/*-theme.xml"
  - "/.github/"
  - Gemfile
  - node_modules/
  - palette.xml
  - README.md
  - LICENSE
  - package.json
  - package-lock.json
  - "/img/octicons/*.md"
  - "/img/octicons/LICENSE"
  - "/img/octicons/script"
  - "/img/adwaita-icons/docs"
  - "/img/adwaita-icons/LICENSE"

