author: Chris Zuber
title: Whiskey Flat Days
url: 'https://whiskeyflatdays.com'
markdown: kramdown
version: 1.0.32
timezone: America/Los_Angeles
lang: en
dir: ltr
charset: utf-8
paginate: 8
paginate_path: "/page-:num/"
viewport: width=device-width
robots: 'follow, index'
referrer: same-origin
manifest: /manifest.json
tiles-config: /browserconfig.xml
service_worker: 'service-worker.js'
og-type: website
description: "Map and events app for Whiskey Flat Days"
thumbnail:
  url: https://i.imgur.com/Qnvw7I2l.jpg
mobile-web-app-capable: true
canonical: 'https://whiskeyflatdays.com'
keywords:
- whiskey flat
- kernville
- kern valley
- kern river valley
- festival
- events
- parade
- rodeo
- events
- vendor
repository:
  username: kernvalley
  project: whiskey-flat-days
  title: Whiskey Flat Days
social:
  url: https://kernvalley.us
  twitter: kern_valley
  linkedin: company/kernvalley-us
  facebook: KernValley.us
# feed:
#   url: /feed.rss
#   type: application/rss+xml
icons: '/img/icons.svg'
theme-color: '#528ff9'
background-color: '#242424'
# discus-identifier:
google-analytics: UA-156441506-1
# ad-sense:
# webmaster-verifications:
#   google:
#   bing:
scripts:
  development:
  - src: /js/index.js
    type: module
    async: true
  production:
  - src: 'https://cdn.polyfill.io/v3/polyfill.min.js'
    type: text/javascript
    crossorigin: anonymous
  - src: 'https://unpkg.com/@webcomponents/custom-elements@1.3.2/custom-elements.min.js'
    type: 'text/javascript'
    integrity: sha384-d4ryOI4Ng+/P1p3ZWsXqWquUYtNHWo9FMxDmDCQhnvogfIzbSz5DoBDfpmqAEBnV
    crossorigin: annonymous
  - src: /js/index.js
    type: module
    async: true
stylesheets:
  development:
  - href: /css/index.css
    media: all
  production:
  - href: /css/index.css
    media: all
preload:
- href: /img/icons.svg
  as: image
  type: image/svg+xml
appicons:
- src: /img/favicon.svg
  sizes: any
  type: image/svg+xml
- src: /img/icon-512.png
  sizes: 512x512
  type: image/png
- src: /img/icon-192.png
  sizes: 192x192
  type: image/png
screenshots:
- src: 'https://i.imgur.com/uRKaQQQl.png'
  sizes: 640x354
  type: image/png
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author:
      givenName: Chris
      familyName: Zuber
      url: 'https://shgysk8zer0.github.io'
      gravatar: '43578597e449298f5488c2407c8a8ae5'
      github: shgysk8zer0
      twitter: shgysk8zer0
      linkedin: chris-zuber-455346141/
    publisher:
      name: 'KernValley.US'
      url: 'https://kernvalley.us'
      logo:
        url: 'https://kernvalley.us/img/icon-256.png'
    permalink: /posts/:categories/:year/:month/:day/:title/
    comments: true
    ads: false
    index: true
- scope:
    path: _drafts
  values:
    layout: post
    author:
      givenName: Chris
      familyName: Zuber
      url: 'https://shgysk8zer0.github.io'
      gravatar: '43578597e449298f5488c2407c8a8ae5'
      github: 'shgysk8zer0'
      twitter: shgysk8zer0
    publisher:
      name: 'KernValley.US'
      url: 'https://kernvalley.us'
      logo:
              url: 'https://kernvalley.us/img/icon-256.png'
    permalink: /posts/:categories/:year/:month/:day/:title/
    comments: false
    ads: false
plugins:
- jekyll-gist
- jekyll-youtube
- jekyll-admin
- jekyll-watch
- jekyll-paginate
exclude:
- ".gitkeep"
- "*.rb"
- "*.gemspec"
- "*.php"
- "*.sh"
- "*.csv"
- "*.sfd"
- "*.ai"
- "*.psd"
- "*.sketch"
- "*.yml"
- "*.lock"
- "*.log"
- "*.config.js"
- ".gitkeep"
- docs/
- "/.github/"
- Gemfile
- node_modules/
- palette.xml
- README.md
- LICENSE
- "/img/octicons/*.md"
- "/img/octicons/LICENSE"
- "/img/octicons/script"
- "/img/adwaita-icons/docs"
- "/img/adwaita-icons/LICENSE"
