---
name: Whiskey Flat Days
shortName: Whiskey Flats
version: 2.0.6-a
start_url: /?utm_source=paw&utm_medium=web
display: standalone
description: "Map and events app for Whiskey Flat Days"
icons-file: /img/icons.svg
theme:
  color: '#007bff'
  background: '#242424'
shortcuts:
- name: Events
  url: /events/
  description: List of events for Whiskey Flat Days
  icons:
  - src: /img/jumplist/events-192.png
    type: image/png
    sizes: 192x192
  - src: /img/jumplist/events-144.png
    type: image/png
    sizes: 144x144
  - src: /img/jumplist/events-96.png
    type: image/png
    sizes: 96x96
  - src: /img/jumplist/events-72.png
    type: image/png
    sizes: 72x72
  - src: /img/jumplist/events-48.png
    type: image/png
    sizes: 48x48
  - src: /img/jumplist/events-36.png
    type: image/png
    sizes: 36x36
- name: Map
  url: /map/
  description: Map of vendors and events for Whiskey Flat Days
  icons:
  - src: /img/jumplist/map-192.png
    type: image/png
    sizes: 192x192
  - src: /img/jumplist/map-144.png
    type: image/png
    sizes: 144x144
  - src: /img/jumplist/map-96.png
    type: image/png
    sizes: 96x96
  - src: /img/jumplist/map-72.png
    type: image/png
    sizes: 72x72
  - src: /img/jumplist/map-48.png
    type: image/png
    sizes: 48x48
  - src: /img/jumplist/map-36.png
    type: image/png
    sizes: 36x36
categories:
- travel
- navigation
- lifestyle
- news
- social
features:
- List of events and vendors for Whiskey Flat Days
- Searchable map containing markers for attractions, businesses, and vendors
- Offline access on supported devices
- Jumplist / shortcuts to events and map pages
- Easy sharing to Facebook, Twitter, text message, and any app installed on your device
- Local weather so you know whether to pack sunscreen or an umbrella
icons:
- src: /img/favicon.svg
  type: image/svg+xml
  sizes: 150x150
  purpose: maskable any
- src: /img/apple-touch-icon.png
  rel: apple-touch-icon
  type: image/png
  sizes: 180x180
- src: /img/icon-512.png
  type: image/png
  sizes: 512x512
  purpose: maskable any
- src: /img/icon-192.png
  type: image/png
  sizes: 192x192
  purpose: maskable any
- src: /img/icon-32.png
  type: image/png
  sizes: 32x32
- src: /img/icon-16.png
  type: image/png
  sizes: 16x16
screenshots:
- src: 'https://i.imgur.com/Qnvw7I2l.jpg'
  sizes: 640x266
  type: image/jpeg
related_applications:
- platform: play
  id: com.whiskey_flats.twa
